##### We have the Suv car purchased data. We have to predict based on the curent data, weather the new customer will purchase or not.

In [1]:
#import data using pandas
import pandas as pd
data = pd.read_csv(r"E:\Suhani\Notes\Data Science\Data\Suv_data_csv.csv")
data= pd.DataFrame(data)
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
#About the data
print("About the data: ",data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
About the data:  None


In [3]:
#if 0 = purchased and 1 = not Purchased, calculate the sum of each
print("Number of puchased and unpurchased: ",data["Purchased"].value_counts())

Number of puchased and unpurchased:  0    257
1    143
Name: Purchased, dtype: int64


In [5]:
#Since gender is in string format transform it into numerical
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
new_gender = le.fit_transform(data["Gender"])
new_gender = pd.DataFrame(new_gender)
print("Gender: ",new_gender)

Gender:       0
0    1
1    1
2    0
3    0
4    1
..  ..
395  0
396  1
397  0
398  1
399  0

[400 rows x 1 columns]


In [6]:
data.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [8]:
#concatinating the columns and renaming the column
x = pd.concat([data[["Age","EstimatedSalary"]],new_gender],join = 'outer',axis=1)
x.columns=x.columns.astype(str)
x.columns = ["Age", "EstimatedSalary", "Gender"]
print(x.columns)
#Convert x into dataframe
x=pd.DataFrame(x)
print(x)

y = data["Purchased"]
print(y)

Index(['Age', 'EstimatedSalary', 'Gender'], dtype='object')
     Age  EstimatedSalary  Gender
0     19            19000       1
1     35            20000       1
2     26            43000       0
3     27            57000       0
4     19            76000       1
..   ...              ...     ...
395   46            41000       0
396   51            23000       1
397   50            20000       0
398   36            33000       1
399   49            36000       0

[400 rows x 3 columns]
0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64


In [9]:
#Standardise the data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
std=scaler.fit_transform(x)
print(std)

[[-1.78179743 -1.49004624  1.02020406]
 [-0.25358736 -1.46068138  1.02020406]
 [-1.11320552 -0.78528968 -0.98019606]
 ...
 [ 1.17910958 -1.46068138 -0.98019606]
 [-0.15807423 -1.07893824  1.02020406]
 [ 1.08359645 -0.99084367 -0.98019606]]


In [10]:
#Split the data into train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(std,y,test_size=0.25,random_state=1)

In [11]:
#shape of train and test data
print("Shape of x_train: ",x_train.shape)
print("Shape of x_test: ",x_test.shape)
print("Shape of y_train: ",y_train.shape)
print("Shape of y_test: ",y_test.shape)

Shape of x_train:  (300, 3)
Shape of x_test:  (100, 3)
Shape of y_train:  (300,)
Shape of y_test:  (100,)


In [12]:
#use logisticRegression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

#use Naive Bayes model
from sklearn.naive_bayes import GaussianNB
model1 = GaussianNB()
model1.fit(x_train, y_train)

GaussianNB()

In [14]:
#Accuracy of training data using Logistic regression
from sklearn.metrics import accuracy_score
y_train_predictiction = model.predict(x_train)
training_data_accuracy = accuracy_score(y_train_predictiction,y_train)

#Accuracy score of training data using Naive Bayes
from sklearn.metrics import accuracy_score
y_train_predictiction1 = model1.predict(x_train)
training_data_accuracy1 = accuracy_score(y_train_predictiction1,y_train)

In [15]:
print("Accuracy of training data using Logistic regression: ",training_data_accuracy)
print("Accuracy of training data using Naive Bayes: ",training_data_accuracy1)

Accuracy of training data using Logistic regression:  0.8433333333333334
Accuracy of training data using Naive Bayes:  0.88


In [16]:
#Accuracy score of test data using logistic regression
from sklearn.metrics import accuracy_score
y_test_prediction = model.predict(x_test)
testing_data_accuracy = accuracy_score(y_test_prediction,y_test)

#Accuracy score of test data using Naive Bayes
y_test_prediction1 = model1.predict(x_test)
test_data_accuracy1 = accuracy_score(y_test_prediction1,y_test)

In [17]:
print("Accuracy of Testing Data using Logistic regression: ",testing_data_accuracy)
print("Accuracy of Testing Data using naive Bayes: ",test_data_accuracy1)

Accuracy of Testing Data using Logistic regression:  0.82
Accuracy of Testing Data using naive Bayes:  0.87


In [17]:
print("Based on the accuracy score we say that Naive Bayes Algorithm is better to use.")

Based on the accuracy score we say that Naive Bayes Algorithm is better to use.


In [20]:
#Predicting for new data
new_data = (29,80000,1)

#Convert it into an array
import numpy as np
new_data_np_array = np.asarray(new_data)

#Reshape the data
new_data_reshape=new_data_np_array.reshape(1,-1)

#std the data
std_new_data = scaler.transform(new_data_reshape)
print(std_new_data)

#fit the new data to the Naive Bayes model
prediction = model.predict(std_new_data)
prediction1 = model1.predict(std_new_data)
print(prediction)
print(prediction1)

#Conclude
if prediction==0:
    print("The customer is going to purchase the car")
else:
    print("The customer is not going to purchase the car")

if prediction1==0:
    print("The customer is going to purchase the car")
else:
    print("The customer is not going to purchase the car")


[[-0.82666613  0.30121002  1.02020406]]
[0]
[0]
The customer is going to purchase the car
The customer is going to purchase the car


C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
